### ISSUE TITLE
readers don't want to sign into wordpress

### ISSUE THREAD

**Issue by debperelman** [a8cteam51/smittenkitchen#106]
I've gotten a stack of comments (and emails) complaining about various aspects of Wordpress sign-ins. 

It sounds like if they have an email address that's associated with a Wordpress account anywhere, it's signing them in under that and using that information, even if they never had this before and don't want to use it.

Another one, verbatim, from one of my longest-time readers sounds similar: 
I have an old, attempted and abandoned blogsite that I FAILED at years ago on Wordpress.  When I try to sign in to leave a comment on your site, Wordpress recognizes my email address (that I've always used here and everywhere else, too) and wants me to sign into my old Wordpress account in order to leave a comment on your blog.  Not only can I not remember what I called the blog or my username there, I don't want to sign in under Wordpress.  Period!  Is there a way I get around this? 

It would be my preference to have NO Wordpress login option -- either forced or chosen. I've never used this on the site, readers have never requested it, and nobody ever complained. Can we bring it back to the way it was? Thanks.

**Comment by sarahmonster** [comment]
I'm going to close this since it isn't something we're able to change without moving platforms entirely, and there are lots of workarounds as detailed above.

I understand that users are frustrated, but this is a common response when much-loved sites change. (Think of the uproar that happens when Facebook changes almost anything.) While there's often some initial discontent, people tend to adapt—and often come to prefer the improvements—once the initial surprise has worn down.

If it's still a major problem for users in a few months' time, please re-open the issue and we can discuss options.

Cheers!
