### ISSUE TITLE
trouble with search

### ISSUE THREAD

**Issue by debperelman** [a8cteam51/smittenkitchen#111]
I'm getting a lot of feedback from readers about the new search not working as well as the old search. For example, a search for crepe or crepes doesn't bring up a big recent post for https://smittenkitchen.com/2016/05/failproof-crepes-a-crepe-party/ but it does bring up a lot of unrelated results (raspberry crushed ice, strawberry griddle cakes) that may or may not have linked to a crepe post at one point. I have many examples from non-crepe searches too, but this gives the idea. Is there a way to finetune this? With a site 1000 recipes deep, it goes without saying that search is the number one way people find what they're looking for.

Update to note that I'm pretty sure the issue with the above is that it's not reading the word crepe because there's an accent over the e. I suppose this means that the search crawls text and not urls? I am getting a lot of complaints, however. I used Google Search before. The results were not pretty, but I never heard from readers that couldn't find things.

**Comment by sarahmonster** [comment]
I've added a plugin to the site that should improve search performance across the board, in situations like these and others as well. Testing for crepe returns lots of crepes, which seems to give the expected result now, for both the special character and otherwise:

https://smittenkitchen.com/?s=cr%C3%AApe
https://smittenkitchen.com/?s=crepe

This should solve search problems, but please let me know if there are any other specific issues here.
