### ISSUE TITLE
problems saving with evernote, pepperplate, paprika, nyt app

### ISSUE THREAD

**Issue by debperelman** [a8cteam51/smittenkitchen#125]
I've been getting a lot of emails and comments from readers that since the redesign they haven't been able to save recipes to the various apps they used before to do so. This is not something I know a lot about because we never did anything on our end, to the best of my knowledge, to enable this. But, it has changed and readers want it back. Do you know anything about the way these sites work and interact with Wordpress, and what might have changed? Thanks.

**Comment by debperelman** [comment]
I'm not sure if this relates to this or RSS concerns, but a reader pointed out to me that Pocket (a bookmarking site) is only saving the recipes and not the posts - it's like the opposite of the RSS feed. It was working before the redesign. [See here for an example](https://getpocket.com/a/read/1362266492).

**Comment by michiecat** [comment]
@debperelman what happens when readers try to save recipes? Do they get an error or some kind of message?

**Comment by debperelman** [comment]
From comments I've received about Evernote alone, readers say the following: 

1. "any idea why Evernote flames out and refuses to clip pages?"
2. "However, my (kind of insane) recipe organization system uses Evernote, and the Evernote webclipper *really* doesn’t like the new formatting of the page. All of the paragraphs overlap with one-another, and I have to go through, remove all line breaks, and put in new ones.
3. Not expecting a fix (at least any time soon) but I figured I’d better say something so you knew there was an area for improvement."
4. "When I copy the ingredient list it completely looses its structure and basically just becomes one long sentence of ingredients. Would be great if that could be fixed. Hmm just tried copying it into word – bullet points still there. Able to copy it from there into evernote just fine. So this might be an evernote bug and not yours."
5. "On the old version, I would hit the print icon and only the recipe would export to my Evernote recipe file. Now, if I hit print, it actually looks for printer and I’m unable to just export the recipe. I don’t really want to upload the entire segment, including the comments. Of course I could just highlight the recipe and do a copy and paste."

**Comment by debperelman** [comment]
Comments about the other recipe boxes not working are less detailed:

1. "Just tried to import a recipe to Pepperplate and was denied."
2. "Did something in the new site break Pepperplate integration? It used to be so easy to import recipes."
3. "Won’t import into Pepperplate. Can you fix it?"
4. "Since the demise of Ziplist (by Epicurious, ugh!), I save all my web recipes to my New York Times recipe box. There are a few websites that do not allow me to save things there, and unfortunately, your newly revised website has become one. I do hope something can be done so I can keep your wonderful recipes within easy access without printing them all out. "
5. "Deb, I can no longer save a recipe to my NYTimes Cooking Recipe Box and there are lots more ads. Any suggestions?"

**Comment by sarahmonster** [comment]
These all sound like separate issues, unfortunately. Since they're related to third-party sites, I don't know how much control we have over their integration. 

For instance, it looks as though Pepperplate has built a custom scraper for its "supported sites":

<img width="637" alt="screen shot 2016-08-08 at 16 49 39" src="https://cloud.githubusercontent.com/assets/376315/17486764/fa264e3a-5d89-11e6-9ba6-76ffb4d1799b.png">

...and that's why the new site is no longer supported—the recipe is formatted slightly differently. I would recommend emailing them at either feedback@pepperplate.com or support@pepperplate.com and asking them to update their scripts. I'm not sure if Pepperplate is still being actively developed, but it's worth asking. I am guessing that their import process is entirely manual.

As far as other sites are concerned, I think again, we'd need to contact the sites directly with support requests, to ask whether it's an issue on our end. If you—or your users—would be able to directly communicate with the relevant services to ask why the data isn't being copied over properly, we can make changes as required.

**Comment by debperelman** [comment]
I will try to reach out but please keep in mind that every one of these integrations (plus more I haven't listed here) worked before we redesigned and they don't now -- we broke this, not them. Perhaps it's an easy fix. I'll let you know when I learn more.

**Comment by sarahmonster** [comment]
A bit more information on this thread: I just tested Paprika out, and it looks like the recipe formatting helps out—probably because we've implemented structured data for the recipes:

![img_0370](https://cloud.githubusercontent.com/assets/376315/17675576/35f96b70-6322-11e6-9872-7981402c9991.jpg)
![img_0371](https://cloud.githubusercontent.com/assets/376315/17675575/35f9458c-6322-11e6-9dfb-18578c22c195.jpg)

However, older posts without the recipe markup (https://smittenkitchen.com/2015/08/takeout-style-sesame-noodles-with-cucumber/ for example) just give a "sorry, couldn't save recipe" error—no more information.

**Comment by debperelman** [comment]
I haven't gotten a response from Pepperplate but as at least 980 of the 1100 recipes on SK aren't yet in shortcode, I really need it to work as it used to for the rest of them. Thanks.

**Comment by debperelman** [comment]
Do we have any progress on this? In the 5.5 weeks since we launched the design, I've received _hundreds_ of comments and emails from readers frustrated that their NYT/Pepperplate/Evernote integrations worked before and don't now. I keep telling them we're working on it, but I am mostly hoping we can just get back the functionality that was always on the site. These outside bookmarking service are a big way that readers organize web recipes, and it's keeping them from cooking recipes as often on SK as they used to. Thank you.

**Comment by sarahmonster** [comment]
The problem with this bug—and the reason why it's hard to fix—is that it relates to third-party services that we have no control over. We don't have super concrete bug reports to follow, and we can't see the errors that are happening with these third-party services. There were many, many changes to the site when we re-launched, but the data is actually much better structured now, so it should be easier for third-party sites to access it. 

In order to resolve the issue, we need to do two things: 1) isolate the actual errors that are occurring and reproducible and 2) contact the developers of these services to determine what the issue is.

I'm going to break this down by service, since the reports are all quite different. 

**Pepperplate:** cannot parse any recipes anymore. Pending developer response, but seems that they need to update their algorithms to work with the updated site structure.

**Paprika:**[ I tested Paprika above](https://github.com/a8cteam51/smittenkitchen/issues/125#issuecomment-239894224) and it seems to work quite well, barring a few posts that don't work properly. ("sorry, couldn't save recipe" error.) It also captures the extra recipe metadata we've added, which it wouldn't have done before.

**Evernote:** I tested this and it seemed to copy fine. (See https://www.evernote.com/shard/s651/sh/6c299295-7119-46b5-9c09-6512ae2c0ec7/2cf47a134edc19c883604016d9507cb0) However, when using the web clipper, I get "no internet connection" error. On other sites, the icon just turns blue and doesn't clip anything. This seems like an error with Evernote, rather than the site. Have any of your users contacted Evernote's support?

**NYT Recipe Box:** In my testing, this seems to work as expected:
<img width="544" alt="screen shot 2016-08-25 at 02 20 42" src="https://cloud.githubusercontent.com/assets/376315/17953348/a0b6a082-6a6a-11e6-8ca8-d476572dd809.png"> 
Can you be more specific about the errors people are experiencing?

**Comment by JRLLRJ** [comment]
I can't seem to save many recent recipes using Paprika -- I get no error message... just nothing happens.  Very odd because Paprika usually has seemed very smart about how to scrape the info.... It is frustrating.... and damaging to the smitten kitchen brand since I think these sorts of apps are widely used.  This is sad because I don't think there's a better recipe source out there.... with serious eats tied in value but for general cooking testing rather than recipes.

**Comment by sarahmonster** [comment]
@JRLLRJ I'm not having the same issues with Paprika—the new recipes actually work much better and have more information available (serving sizes, etc). Can you let me know how you're saving them (ie, are you using a browser extension) and which specific recipes are failing, so I can try to replicate myself?

**Comment by JRLLRJ** [comment]
So, interesting... if I open today's recipe
https://smittenkitchen.com/2016/09/indian-spiced-cauliflower-soup/
WITHIN the paprika browser, it saves it.
If i use the bookmark "save recipe" that used to work and works on other sites, it does not save it.

**Comment by JRLLRJ** [comment]
(Safari by the way) - same thing with the recent clams recipe
https://smittenkitchen.com/2016/09/garlic-wine-and-butter-steamed-clams/

**Comment by sarahmonster** [comment]
I tested the bookmarklet out in Safari with the same recipe, and it seems to work properly:

![paprika](https://cloud.githubusercontent.com/assets/376315/18886195/d464010e-84e6-11e6-8308-b65bc37d7122.gif)

It says "Downloading recipe..." and then "recipe saved!" Then the recipes are available via the Paprika app. (The app currently isn't syncing properly, but that's almost surely a Paprika issue.)

Is this what you're seeing as well, or is there a different result? Do recipes on other sites work? Have you tried contacting Paprika's support desk to see what the issue is?

**Comment by JRLLRJ** [comment]
nothing happens - nothing at all.  So far, other sites are working (e.g.,
serious eats)

**Comment by sarahmonster** [comment]
Hm. I can't replicate this at all, which makes it hard to bugfix. It's worked properly in lots of different browsers for both new and old recipes.  

Which version of Safari are you using? Does it work if you use a different browser? 

Given that I can't replicate the issue, I'd suggest submitting a support request with Paprika—they'll be able to help determine the issue more rapidly, and figure out if it's an issue with the site or not. You can submit a request here: https://paprikaapp.zendesk.com/anonymous_requests/new

**Comment by sarahmonster** [comment]
@debperelman I'm unable to reproduce these issues, and we don't have enough information to work from here, particularly because these are specific issues with different third-party providers. 

If any specific bug reports come in, please do feel free to open them as new issues, and we can evaluate each issue on a case-by-case basis. The more information you can provide (ie: browser used, steps taken, support history/information from the service in particular) the better we'll be able to bugfix & evalute the issue.

**Comment by sadamny** [comment]
I came across this thread while searching for an answer to this.  The switch to HTTPS from HTTP caused it.  I use paprika bookmarklet and can tell it cannot scrape from any site with HTTPS enabled.  SK, Cooks Illustrated and (just now) NY times are the issue, whereas Bon Appetit are not a problem.

So its a technical issue - not something specific to your site.

**Comment by sarahmonster** [comment]
Thanks for the extra information @sadamny! Hopefully that's something Paprika will work on sorting out, since it's going to become more and more prevalent in the future, particularly with Google prioritising https sites over http.
