### ISSUE TITLE
Adjustments to recipe layout

### ISSUE THREAD

**Issue by debperelman** [a8cteam51/smittenkitchen#133]
- I'd like the recipe title to be smaller. Right now it's the same size as the title of the post, which feels unnecessary -- that should be the biggest on the page. It could easily be one or two font size smaller.
- For the information that follows it, servings/time, etc. I'd also like these to use a different smaller font, such as the all-caps but smaller font we use for the date field on the posts. Just a little visual differentiation between header-level information and recipe data.
- I'd like to add another item field to this top section, a "Source" field. It looks best when its right at the top with other top-level information.
- I know I asked this before, but I'm wondering again if we can remove the bullets from the ingredients list. The visual clutter feels unnecessary when looking at a recipe, I think that the ingredients fall in a stack is sufficient enough to show that it's a list.

Thank you.

**Comment by sarahmonster** [comment]
> I'd like the recipe title to be smaller. Right now it's the same size as the title of the post, which feels unnecessary -- that should be the biggest on the page. It could easily be one or two font size smaller.

These two elements aren't the same size at all; the post title is 46px whilst the recipe title is 35.15px. This is more obvious when you look at them side-by-side:

<img width="487" alt="screen shot 2016-08-08 at 16 30 03" src="https://cloud.githubusercontent.com/assets/376315/17485387/7f6bf702-5d85-11e6-8a32-8c4074dc1f10.png">

<img width="683" alt="screen shot 2016-08-08 at 16 34 48" src="https://cloud.githubusercontent.com/assets/376315/17485625/0fedf30c-5d86-11e6-81c9-b044bdacba49.png">

However, I've made the difference even greater. Now the recipe title is 27px:
<img width="664" alt="screen shot 2016-08-08 at 16 44 58" src="https://cloud.githubusercontent.com/assets/376315/17486100/78cafb12-5d87-11e6-969e-3a17c6b1f5d0.png">

> For the information that follows it, servings/time, etc. I'd also like these to use a different smaller font, such as the all-caps but smaller font we use for the date field on the posts. Just a little visual differentiation between header-level information and recipe data.

Done. Note that all-caps is a bit harder to read than lowercase, so it's best to keep the text strings here short.

> I'd like to add another item field to this top section, a "Source" field. It looks best when its right at the top with other top-level information.

This would require adding new functionality for all users of WordPress.com, which is a larger change since it affects so many users. How would you envision this working? Would you just provide a link to the original source, or would there be a string of text as well?

> I know I asked this before, but I'm wondering again if we can remove the bullets from the ingredients list. The visual clutter feels unnecessary when looking at a recipe, I think that the ingredients fall in a stack is sufficient enough to show that it's a list.

Done. This do make the lists a bit harder to parse, but you're free to change it back at any point if users find it hard to read.

**Comment by debperelman** [comment]
Thanks for making these adjustments, and the clarification.

> I'd like to add another item field to this top section, a "Source" field. It looks best when its right at the top with other top-level information.
> 
> This would require adding new functionality for all users of WordPress.com, which is a larger change since it affects so many users. How would you envision this working? Would you just provide a link to the original source, or would there be a string of text as well?

It would have a link (where appropriate; not all recipes reference an outside source) and usually some text with it. If we cannot add the functionality, can we change the styling of the field so that it appears at the top like the other items, in a similar font treatment? For me, it's header-level information, so it belongs up there and not in the notes. Thank you.

**Comment by sarahmonster** [comment]
I've just pushed a change to the recipe shortcode that adds a source field. It's pretty straightforward; basically you'll add the source text and the URL as parameters to the main `[recipe]` shortcode, like this:

`[recipe ... source="Recipe source" sourceurl="http://link.com"]`

You can omit the URL and only the text will appear. If the URL is included, the text will link to that URL. 

I've added it to this post, so you can see it in action: https://smittenkitchen.com/2016/11/roasted-cauliflower-with-pumpkin-seeds-brown-butter-and-lime/

<img width="673" alt="screenshot 2016-11-04 18 18 24" src="https://cloud.githubusercontent.com/assets/376315/20017344/181dc1c2-a2bb-11e6-8f16-47b4f3e93a2a.png">

If you have any questions or revisions, do let us know!
