### ISSUE TITLE
newsletter signup field: how to use elsewhere

### ISSUE THREAD

**Issue by debperelman** [a8cteam51/smittenkitchen#134]
I have a few places throughout the site where I've used a Mailchimp signup field before that stopped working after the redesign. (I went ahead and just removed the code here: https://smittenkitchen.com/subscribe/ but here -- at the end of the post --https://smittenkitchen.com/2015/10/chocolate-peanut-and-pretzel-brittle/ I have not yet.) My question is: can I use the newsletter signup form Team 51 created in other parts of the site, such as on these pages? Thanks.

**Comment by sarahmonster** [comment]
For security reasons, our editor will strip out certain bits of HTML, which means you won't be able to directly paste in a newsletter subscription form. (For more about what you can and can't use, code-wise, see this support article: https://en.support.wordpress.com/code/)

However, in order to make it super-easy to add this form when needed, I've created a custom shortcode that you can use anywhere you'd like in posts or pages. Just drop `[newsletter-signup]` anywhere you'd like the form to appear, and it will!

I've added the shortcode to https://smittenkitchen.com/subscribe/ so you can see an example of how that works as well.

**Comment by debperelman** [comment]
Wow, thank you!

**Comment by debperelman** [comment]
This works on static pages, but not posts? Had the MailChimp form in this post https://smittenkitchen.com/2015/10/oven-fries/ which announced the new newsletter. The code was scrambled, tried to use the newsletter-signup but you can see it doesn't pull it up.

**Comment by sarahmonster** [comment]
The trouble here was with nested shortcodes—because the newsletter shortcode was nested inside the donotprint shortcode, it didn't work properly. I've corrected this now so any nested shortcodes should be respected.
