### ISSUE TITLE
we could use a footer on posts that show on the front page

### ISSUE THREAD

**Issue by debperelman** [a8cteam51/smittenkitchen#135]
Because I show more than one photo from the top (newest) post (and adjust the break after I publish the next new article), it's a little confusing when scrolling down the front page to figure out where one post ends and the next one begins -- the only way a reader can tell is the small tag over the top photo and then the large title underneath it (but at that point, they've already scrolled past the lead photo). The solution would be to create a small footer below each post. 

I'm wondering if it could just mimic the footer on the full post pages (see attached but specifically just one subtle dashed line and one line of information in that small all-caps font)... and here's where it gets messier, which is that this seems to be an ideal place to also move the date down from under the title, just to reduce the visual clutter and empty spaces on the front page. However, on individual posts, it makes sense to keep it there (because there are also the essential "jump to recipe, comments" links. Do you think it's okay if the location of the dates on the front page don't match the location of the dates on the individual pages?
![screen shot 2016-08-03 at 2 41 50 pm](https://cloud.githubusercontent.com/assets/16911319/17377902/d80156e6-5989-11e6-86a6-5f2cb9457b06.png)

I think we'll have enough space on this footer line to add other information, maybe either a comment count (used to have this), social media icons or those jump to recipes/comments links.

**Comment by sarahmonster** [comment]
I think we can move the date to a footer line without it being too disruptive—this isn't vital information, particularly on the front page where the content tends to be quite new. Comment count, given how active your commenters are, is probably far more useful!

I've set this up for you on my test site—let me know if you'd like to push it to the production site!

<img width="683" alt="screenshot 2016-11-18 14 36 37" src="https://cloud.githubusercontent.com/assets/376315/20433653/8b2ff392-ad9c-11e6-8fe9-7b15cec8d4ac.png">

A few notes: we can't do the "jump to recipe" links here because it wouldn't work if the post didn't have a recipe in it—admittedly rare, but would make for an awkward UI. Social links make sense on the full post, but don't make sense on an excerpt—people tend to want to read a post before sharing it, and it's a lot of extra stuff to load so it slows down the page.
