### ISSUE TITLE
Events management integration

### ISSUE THREAD

**Issue by debperelman** [a8cteam51/smittenkitchen#137]
I've looked over the available VIP plugins but didn't see one that fit the bill. I'd like to implement some sort of events calendar for the site where people will be able to copy things to their calendar. This (https://wordpress.org/plugins/the-events-calendar/screenshots/) looks promising, though there might be others just as good. Can I just ... install this or does it need to first be vetted?

**Comment by sarahmonster** [comment]
We need to fully review any plugin that will be added to the theme in order to ensure it meets our security standards—this can take quite some time, depending on the complexity of the plugin, and many readily-available plugins don't meet our [code review and security standards](https://vip.wordpress.com/documentation/vip/code-review-what-we-look-for/).

I've worked with the Events Calendar plugin before and it's quite complex. Code-reviewing and then implementing it would definitely be a big task. What kind of functionality, exactly, are you looking for here? We may be able to sort out a simpler and more straightforward solution.

A couple of suggestions:

[Eventbrite](https://www.eventbrite.com) is a popular third-party system for managing events. It's quite fully-featured and has hooks that allow it to be integrated with a WordPress site.

We also have a [Google Calendar plugin](https://vip.wordpress.com/plugins/google-calendar-events/) available on VIP already. This is a pretty simple plugin but it may be sufficient to meet your needs.

If you can let us know exactly what you're looking for in terms of functionality, we can investigate to see what would be best to meet your needs.

**Comment by sarahmonster** [comment]
Closing this issue since it's been stagnant since August. @debperelman please do feel free to re-open the issue if you'd like to discuss further.
