### ISSUE TITLE
comments sorting and threading still not working correctly

### ISSUE THREAD

**Issue by debperelman** [a8cteam51/smittenkitchen#139]
For example, here is a comment from ANNA:
https://smittenkitchen.com/2016/08/chocolate-peanut-butter-icebox-cake/#comment-843580

- Under the ALL COMMENTS tab you can see multiple responses including one from me. 

- Under the QUESTIONS tab, you can only see her question and no responses from me or anyone else.

Same for this comment from ELLEN M: 
https://smittenkitchen.com/2016/08/chocolate-peanut-butter-icebox-cake/#comment-843577

- Under the ALL COMMENTS tab, there's a response from me.

- Under the QUESTIONS tab, there's no response from me.

And this from KATHY M:
https://smittenkitchen.com/2016/08/chocolate-peanut-butter-icebox-cake/#comment-843566

- This also shows up under I MADE THIS. I'm not sure if she mis-selected or if it shows up by accident, but it shouldn't be there. 

- Under I MADE THIS, you cannot see my comment response.

**Comment by sarahmonster** [comment]
Related comments/fixes in #110.

**Comment by sarahmonster** [comment]
Re: Kathy M's comment:

> This also shows up under I MADE THIS. I'm not sure if she mis-selected or if it shows up by accident, but it shouldn't be there. 

...that's because she selected "I made this" rather than "I have a question." You can edit this for any comment by clicking the "edit" button next to the comment, and changing the comment metadata. (I've done this for you here.)

<img width="800" alt="screen shot 2016-08-22 at 09 15 02" src="https://cloud.githubusercontent.com/assets/376315/17848062/6e98f8f2-6849-11e6-997c-1ca3f97cd26d.png">

**Comment by sarahmonster** [comment]
I've re-worked this code a bit and it seems to work properly now—please do let re-open if that isn't the case, or if further testing is required!
