### ISSUE TITLE
Google AMP Pages Not Showing Template, Comments or Ads

### ISSUE THREAD

**Issue by debperelman** [a8cteam51/smittenkitchen#142]
Google, as you probably know, has introduced AMP web results for mobile and the from SK look all wrong. 

https://smittenkitchen.com/2016/10/winter-squash-pancakes-with-crispy-sage-and-brown-butter/amp/

Less urgent than the design is that ads and comments are missing. More than 50% of site traffic comes from mobile and we're not showing ads to these people. And readers are upset the comments have disappeared.

Can we put this first in the queue? This is a pretty big problem. Thank you.

**Comment by sarahmonster** [comment]
A bit of an explanation of how Google AMP works: these pages only show for Google search results—visitors who type the URL into their browser and visit the site that way won't see them. They're purposefully stripped-down to ensure super-fast load times, and Google has been prioritising AMP-enabled sites in its results. 

You can learn more about how it works here: https://en.support.wordpress.com/google-amp-accelerated-mobile-pages/

While we can customise the appearance of your site's AMP pages to some degree, because of their requirements, I'm not certain we'd be able to include comments or ads. There are [ads specially designed for AMP pages](https://amphtml.wordpress.com/2016/07/19/but-what-about-the-ads/), but that's still quite new—and you'd need to talk to your ad providers to see if that's something they can enable for you.

I've disabled Google AMP from your site entirely. If you'd like to evaluate a custom-designed AMP page, please re-open the issue, and we can evaluate that possibility.
