### ISSUE TITLE
Is there a way to add a comment form to a static page? 

### ISSUE THREAD

**Issue by debperelman** [a8cteam51/smittenkitchen#149]
I'm looking and cannot find a way, sifted through Wordpress forums too, no answer I could apply here. Thank you.

**Comment by sarahmonster** [comment]
Sure is! Here's all the documentation: https://en.support.wordpress.com/forms/contact-form/

The above is the method we used for other contact forms on the site, like the contact page. 

If you have any troubles getting the form set up, please do reopen this issue & we'll help you out with it.

Cheers!

**Comment by debperelman** [comment]
Thanks. Is there a way to add _comments_, as in a comment section. It's not only for communicating with me; I want everyone to see other comments.

**Comment by sarahmonster** [comment]
Ah, I see what you mean. Sorry about that, I'm tired and misread. I've added this for you—you can see it in action on the [FAQ page](https://smittenkitchen.com/about/faq/).

**Comment by debperelman** [comment]
Thank you. Is there a way I can control it? I would like it on a couple pages -- namely book info pages, so people can ask questions there -- but not the vast majority of pages.

**Comment by sarahmonster** [comment]
For sure! You can turn it on and off on a per-page basis, the same way you do for posts: https://en.support.wordpress.com/enable-and-disable-comments-for-published-posts-and-pages/

You can control the site-wide settings by following these instructions:
https://en.support.wordpress.com/enable-disable-comments-for-future-posts-pages/

**Comment by debperelman** [comment]
Hello -- circling back to this, which isn't working the way I'd hoped.

1. All pages now have open comments, and I only wanted to open them on one page.
2. I am not able to open or close the comments on these pages. What this page (https://en.support.wordpress.com/enable-and-disable-comments-for-published-posts-and-pages/) shows isn't what I see. There's no "More options" or "Allow comments" to select or unselect... 

Thank you.

**Comment by sarahmonster** [comment]
Hi @debperelman, the problem here is that comments were originally enabled on the pages, and the comment box was hidden via the theme. In order to reveal the comment box on that single page, we needed to reveal it on all pages where comments were open.

I suspect you may be using the wp-admin view (old interface, grey), rather than the new interface (blue, WordPress.com-specific), which is why those instructions won't work for you. 

If you're using the wp-admin view, you should see this box on every page:
<img width="672" alt="screenshot 2017-06-21 17 49 17" src="https://user-images.githubusercontent.com/376315/27396160-2608fb1e-56aa-11e7-8726-cbbd9cac099a.png">

If you don't see that box, it might be hidden—click on "Screen options" at the top right of the page, and tick the "Discussion" box to reveal it.

Unticking that "allow comments" box should resolve the issue for you. By default, when you create a new page, the box is unticked for pages and ticked for posts, since this is the most typical behaviour. 

Do let us know if you continue having troubles with it!
